name = "honeypotscan-api"
main = "index.ts"
compatibility_date = "2024-01-01"
account_id = "5409b078a5a93cd064a01ec1fd56e675"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "0bee119f31ec4886a684562b4d6f45fb"

# Environment variables (set via wrangler secret)
# ETHERSCAN_API_KEY_1
# ETHERSCAN_API_KEY_2
# ETHERSCAN_API_KEY_3
# ETHERSCAN_API_KEY_4
# ETHERSCAN_API_KEY_5
# ETHERSCAN_API_KEY_6
